/**
 * @enum The paths of the images corresponding to the different assets
 * 
 * @author Eric Ritte, Klaudia Leo, Laura Traub, Niklas Schmidt, Philipp Schumacher
 * @version 1.0.0
 */
AssetPaths = Object.freeze({	
    // Blank
    "blank": "../client/assets/other/blank.png",

    // Tiles
    "tile_default": "../client/assets/tiles/tile.png",
    "tile_selected": "../client/assets/tiles/tile_selected.png",
    "carpet_yellow": "../client/assets/tiles/carpet_yellow.png",
    "carpet_orange": "../client/assets/tiles/carpet_orange.png",
    "carpet_red": "../client/assets/tiles/carpet_red.png",
    "carpet_pink": "../client/assets/tiles/carpet_pink.png",
    "carpet_purple": "../client/assets/tiles/carpet_purple.png",
    "carpet_blue": "../client/assets/tiles/carpet_blue.png",
    "carpet_tosca": "../client/assets/tiles/carpet_tosca.png",
    "carpet_green": "../client/assets/tiles/carpet_green.png",
    "carpet_white": "../client/assets/tiles/carpet_white.png",
    
    // Walls
    "leftwall_default": "../client/assets/walls/wall_left.png",
    "rightwall_default": "../client/assets/walls/wall_right.png",
    
    // Barriers
    "barrier_default": "../client/assets/walls/barrier_default.png",
    "barrier_0": "../client/assets/walls/barrier_0.png",
    "barrier_1": "../client/assets/walls/barrier_1.png",
    "barrier_2": "../client/assets/walls/barrier_2.png",
    "barrier_3": "../client/assets/walls/barrier_3.png",
    "barrier_x": "../client/assets/walls/barrier_x.png",
    "barrier_y": "../client/assets/walls/barrier_y.png",
    
    // Doors
    "leftnonedoor_default": "../client/assets/doors/door_left_default.png",
    "rightnonedoor_default": "../client/assets/doors/door_right_default.png",
    "leftfoyerdoor_default": "../client/assets/doors/door_foyer.png",
    "rightfoyerdoor_default": "../client/assets/doors/door_foyer_alt.png",
    "leftreceptiondoor_default": "../client/assets/doors/door_reception_alt.png",
    "rightreceptiondoor_default": "../client/assets/doors/door_reception.png",
    "leftlecturedoor_default": "../client/assets/doors/door_lecturehall.png",
    "rightlecturedoor_default": "../client/assets/doors/door_lecturehall_alt.png",
    "leftfoodcourtdoor_default": "../client/assets/doors/door_foodcourt_alt.png",
    "rightfoodcourtdoor_default": "../client/assets/doors/door_foodcourt.png",
    
    // Schedule
    "leftschedule_default0": "../client/assets/walls/schedule1.png",
    "leftschedule_default1": "../client/assets/walls/schedule2.png",
    "leftschedule_default2": "../client/assets/walls/schedule3.png",
    
    // Windows
    "leftwindow_default0": "../client/assets/windows/left_small_window_default0.png",
    "rightwindow_default0": "../client/assets/windows/right_small_window_default0.png",
    "leftwindow_default1": "../client/assets/windows/left_small_window.png",
    "rightwindow_default1": "../client/assets/windows/right_small_window_default1.png",
    
    // Plant & Picture Frames
    // "plant_default": "../client/assets/plants/plant.png",
    "rightwallframe_default0": "../client/assets/frames/wallframe1.png",
    "rightwallframe_default1": "../client/assets/frames/wallframe2.png",
    "rightwallframe_default2": "../client/assets/frames/wallframe3.png",
    
    // Logo
    "leftconferencelogo_default0": "../client/assets/logos/conferencelogoLLL1.png",
    "leftconferencelogo_default1": "../client/assets/logos/conferencelogoLLL2.png",
    "leftconferencelogo_default2": "../client/assets/logos/conferencelogoLLL3.png",
    "leftconferencelogo_default3": "../client/assets/logos/conferencelogoLLL4.png",
    "leftconferencelogo_default4": "../client/assets/logos/conferencelogoLLL5.png",
    
    // Seating
    "chair_default_0": "../client/assets/chairs/chair_default_0.png",
    "chair_default_1": "../client/assets/chairs/chair_default_1.png",
    "chair_default_2": "../client/assets/chairs/chair_default_2.png",
    "chair_default_3": "../client/assets/chairs/chair_default_3.png",
    "chair_yellow_0": "../client/assets/chairs/chair_yellow_0.png",
    "chair_yellow_1": "../client/assets/chairs/chair_yellow_1.png",
    "chair_yellow_2": "../client/assets/chairs/chair_yellow_2.png",
    "chair_yellow_3": "../client/assets/chairs/chair_yellow_3.png",
    "chair_orange_0": "../client/assets/chairs/chair_orange_0.png",
    "chair_orange_1": "../client/assets/chairs/chair_orange_1.png",
    "chair_orange_2": "../client/assets/chairs/chair_orange_2.png",
    "chair_orange_3": "../client/assets/chairs/chair_orange_3.png",
    "chair_red_0": "../client/assets/chairs/chair_red_0.png",
    "chair_red_1": "../client/assets/chairs/chair_red_1.png",
    "chair_red_2": "../client/assets/chairs/chair_red_2.png",
    "chair_red_3": "../client/assets/chairs/chair_red_3.png",
    "chair_pink_0": "../client/assets/chairs/chair_pink_0.png",
    "chair_pink_1": "../client/assets/chairs/chair_pink_1.png",
    "chair_pink_2": "../client/assets/chairs/chair_pink_2.png",
    "chair_pink_3": "../client/assets/chairs/chair_pink_3.png",
    "chair_purple_0": "../client/assets/chairs/chair_purple_0.png",
    "chair_purple_1": "../client/assets/chairs/chair_purple_1.png",
    "chair_purple_2": "../client/assets/chairs/chair_purple_2.png",
    "chair_purple_3": "../client/assets/chairs/chair_purple_3.png",
    "chair_blue_0": "../client/assets/chairs/chair_blue_0.png",
    "chair_blue_1": "../client/assets/chairs/chair_blue_1.png",
    "chair_blue_2": "../client/assets/chairs/chair_blue_2.png",
    "chair_blue_3": "../client/assets/chairs/chair_blue_3.png",
    "chair_tosca_0": "../client/assets/chairs/chair_tosca_0.png",
    "chair_tosca_1": "../client/assets/chairs/chair_tosca_1.png",
    "chair_tosca_2": "../client/assets/chairs/chair_tosca_2.png",
    "chair_tosca_3": "../client/assets/chairs/chair_tosca_3.png",
    "chair_green_0": "../client/assets/chairs/chair_green_0.png",
    "chair_green_1": "../client/assets/chairs/chair_green_1.png",
    "chair_green_2": "../client/assets/chairs/chair_green_2.png",
    "chair_green_3": "../client/assets/chairs/chair_green_3.png",
    "chair_white_0": "../client/assets/chairs/chair_white_0.png",
    "chair_white_1": "../client/assets/chairs/chair_white_1.png",
    "chair_white_2": "../client/assets/chairs/chair_white_2.png",
    "chair_white_3": "../client/assets/chairs/chair_white_3.png",
    "chair_swivel_0": "../client/assets/chairs/chair_swivel_0.png",
    "chair_swivel_1": "../client/assets/chairs/chair_swivel_1.png",
    "chair_swivel_2": "../client/assets/chairs/chair_swivel_2.png",
    "chair_swivel_3": "../client/assets/chairs/chair_swivel_3.png",
    
    "sofa_front_0": "../client/assets/chairs/sofa_front_0.png",
    "sofa_middle_0": "../client/assets/chairs/sofa_middle_0.png",
    "sofa_back_0": "../client/assets/chairs/sofa_back_0.png",
    "sofa_front_1": "../client/assets/chairs/sofa_front_1.png",
    "sofa_middle_1": "../client/assets/chairs/sofa_middle_1.png",
    "sofa_back_1": "../client/assets/chairs/sofa_back_1.png",
    "sofa_front_2": "../client/assets/chairs/sofa_front_2.png",
    "sofa_middle_2": "../client/assets/chairs/sofa_middle_2.png",
    "sofa_back_2": "../client/assets/chairs/sofa_back_2.png",
    "sofa_front_3": "../client/assets/chairs/sofa_front_3.png",
    "sofa_middle_3": "../client/assets/chairs/sofa_middle_3.png",
    "sofa_back_3": "../client/assets/chairs/sofa_back_3.png",
    
    // Tables
    "table_default": "../client/assets/tables/table.png",
    "table_front_x": "../client/assets/tables/table_front_x.png",
    "table_middle_x": "../client/assets/tables/table_middle_x.png",
    "table_back_x": "../client/assets/tables/table_back_x.png",
    "table_front_y": "../client/assets/tables/table_front_y.png",
    "table_middle_y": "../client/assets/tables/table_middle_y.png",
    "table_back_y": "../client/assets/tables/table_back_y.png",
    
    // Counters
    "counter_default": "../client/assets/counters/counter_default.png",
    "counter_front_x": "../client/assets/counters/counter_front_x.png",
    "counter_middle_x": "../client/assets/counters/counter_middle_x.png",
    "counter_back_x": "../client/assets/counters/counter_back_x.png",
    "counter_front_y": "../client/assets/counters/counter_front_y.png",
    "counter_middle_y": "../client/assets/counters/counter_middle_y.png",
    "counter_back_y": "../client/assets/counters/counter_back_y.png",
    "counter_corner_left": "../client/assets/counters/counter_corner_left.png",
    "counter_corner_front": "../client/assets/counters/counter_corner_front.png",
    "counter_corner_right": "../client/assets/counters/counter_corner_right.png",
    "counter_corner_back": "../client/assets/counters/counter_corner_back.png",
    
    // Cupboards
    "cupboard_left": "../client/assets/cupboards/cupboard_left.png",
    "cupboard_left_alt": "../client/assets/cupboards/cupboard_left_alt.png",
    "cupboard_left_shelf": "../client/assets/cupboards/cupboard_left_shelf.png",
    "cupboard_left_books": "../client/assets/cupboards/cupboard_left_books.png",
    "cupboard_left_books_alt": "../client/assets/cupboards/cupboard_left_books_alt.png",
    "cupboard_right": "../client/assets/cupboards/cupboard_right.png",
    "cupboard_right_alt": "../client/assets/cupboards/cupboard_right_alt.png",
    "cupboard_right_shelf": "../client/assets/cupboards/cupboard_right_shelf.png",
    "cupboard_right_books": "../client/assets/cupboards/cupboard_right_books.png",
    "cupboard_right_books_alt": "../client/assets/cupboards/cupboard_right_books_alt.png",
    "cupboard_left_back": "../client/assets/cupboards/cupboard_left_back.png",
    "cupboard_right_back": "../client/assets/cupboards/cupboard_right_back.png",
    "cupboard_corner_left": "../client/assets/cupboards/cupboard_corner_left.png",
    "cupboard_corner_front": "../client/assets/cupboards/cupboard_corner_front.png",
    "cupboard_corner_right": "../client/assets/cupboards/cupboard_corner_right.png",
    "cupboard_corner_back": "../client/assets/cupboards/cupboard_corner_back.png",
    
    "sideboard_left": "../client/assets/cupboards/sideboard_left.png",
    "sideboard_left_alt": "../client/assets/cupboards/sideboard_left_alt.png",
    "sideboard_left_shelf": "../client/assets/cupboards/sideboard_left_shelf.png",
    "sideboard_left_books": "../client/assets/cupboards/sideboard_left_books.png",
    "sideboard_left_books_alt": "../client/assets/cupboards/sideboard_left_books_alt.png",
    "sideboard_right": "../client/assets/cupboards/sideboard_right.png",
    "sideboard_right_alt": "../client/assets/cupboards/sideboard_right_alt.png",
    "sideboard_right_shelf": "../client/assets/cupboards/sideboard_right_shelf.png",
    "sideboard_right_books": "../client/assets/cupboards/sideboard_right_books.png",
    "sideboard_right_books_alt": "../client/assets/cupboards/sideboard_right_books_alt.png",
    "sideboard_left_back": "../client/assets/cupboards/sideboard_left_back.png",
    "sideboard_right_back": "../client/assets/cupboards/sideboard_right_back.png",
    "sideboard_corner_left": "../client/assets/cupboards/sideboard_corner_left.png",
    "sideboard_corner_front": "../client/assets/cupboards/sideboard_corner_front.png",
    "sideboard_corner_right": "../client/assets/cupboards/sideboard_corner_right.png",
    "sideboard_corner_back": "../client/assets/cupboards/sideboard_corner_back.png",
    
    // Floordecoration
    "floordecoration_plant": "../client/assets/decoration/floordecoration_plant.png",
    "floordecoration_palm": "../client/assets/decoration/floordecoration_palm.png",
    "floordecoration_palmtree": "../client/assets/decoration/floordecoration_palmtree.png",
    "floordecoration_guitar": "../client/assets/decoration/floordecoration_guitar.png", 
    "floordecoration_balls": "../client/assets/decoration/floordecoration_balls.png",   
    
    // Tabledecoration
    "tabledecoration_plant": "../client/assets/decoration/tabledecoration_plant.png",
    "tabledecoration_palm": "../client/assets/decoration/tabledecoration_palm.png",
    "tabledecoration_cactus": "../client/assets/decoration/tabledecoration_cactus.png",
    "tabledecoration_flowers": "../client/assets/decoration/tabledecoration_flowers.png",
    "tabledecoration_succulents": "../client/assets/decoration/tabledecoration_succulents.png",
    "tabledecoration_balls": "../client/assets/decoration/tabledecoration_balls.png",
    "tabledecoration_paper_0": "../client/assets/decoration/tabledecoration_paper_0.png",
    "tabledecoration_paper_1": "../client/assets/decoration/tabledecoration_paper_1.png",
    "tabledecoration_paper_2": "../client/assets/decoration/tabledecoration_paper_2.png",
    "tabledecoration_paper_3": "../client/assets/decoration/tabledecoration_paper_3.png",
    "tabledecoration_pen_0": "../client/assets/decoration/tabledecoration_pen_0.png",
    "tabledecoration_pen_1": "../client/assets/decoration/tabledecoration_pen_1.png",
    "tabledecoration_pen_2": "../client/assets/decoration/tabledecoration_pen_2.png",
    "tabledecoration_pen_3": "../client/assets/decoration/tabledecoration_pen_3.png",
    "tabledecoration_tablet_x": "../client/assets/decoration/tabledecoration_tablet_x.png",
    "tabledecoration_tablet_y": "../client/assets/decoration/tabledecoration_tablet_y.png",
    "tabledecoration_coffee": "../client/assets/decoration/tabledecoration_coffee.png",
    "tabledecoration_coffeegroup": "../client/assets/decoration/tabledecoration_coffeegroup.png",
    "tabledecoration_books_back": "../client/assets/decoration/tabledecoration_books_back.png",
    "tabledecoration_books_left": "../client/assets/decoration/tabledecoration_books_left.png",
    "tabledecoration_books_right": "../client/assets/decoration/tabledecoration_books_right.png",
    "tabledecoration_books": "../client/assets/decoration/tabledecoration_books.png",
    "tabledecoration_computer_0": "../client/assets/decoration/tabledecoration_computer_0.png",
    "tabledecoration_computer_3": "../client/assets/decoration/tabledecoration_computer_3.png",
    "tabledecoration_countertop_x_1": "../client/assets/decoration/tabledecoration_countertop_x_1.png",
    "tabledecoration_countertop_x_2": "../client/assets/decoration/tabledecoration_countertop_x_2.png",
    "tabledecoration_countertop_y_1": "../client/assets/decoration/tabledecoration_countertop_y_1.png",
    "tabledecoration_countertop_y_2": "../client/assets/decoration/tabledecoration_countertop_y_2.png",
    "tabledecoration_plates": "../client/assets/decoration/tabledecoration_plates.png",
    
    // Explanations
    "explanation_left": "../client/assets/decoration/explanation_left.png",
    "explanation_right": "../client/assets/decoration/explanation_right.png",
    "explanation_barrier_left": "../client/assets/decoration/explanation_barrier_left.png",
    "explanation_barrier_right": "../client/assets/decoration/explanation_barrier_right.png",
    "explanation_0": "../client/assets/decoration/explanation_0.png",
    "explanation_1": "../client/assets/decoration/explanation_1.png",
    "explanation_2": "../client/assets/decoration/explanation_2.png",
    "explanation_3": "../client/assets/decoration/explanation_3.png",
    
    
    // Food & Drinks
    "drinks_default": "../client/assets/other/Drinks.png",
    "koeriWurst_default": "../client/assets/food/koeriWurscht.png",
    "koeriWurst_bothSides": "../client/assets/food/koeriWurscht_bothSides.png",
    "koeriWurst_upperSide": "../client/assets/food/koeriWurscht_upperSide.png",
    "koeriWurst_lowerSide": "../client/assets/food/koeriWurscht_lowerSide.png",
    "tea_default": "../client/assets/food/tea.png",
});

if (typeof module === 'object' && typeof exports === 'object') {
    module.exports = AssetPaths;
}
